blank_issues_enabled: true
contact_links:
  - name: 询问问题
    url: https://github.com/DuckDuckStudio/Chinese_git/discussions/new
    about: 你对某事感到疑惑？发起一个新的讨论以向社区寻求答案。
  - name: 查看已经打开的问题
    url: https://github.com/DuckDuckStudio/Chinese_git/issues
    about: 请确认你的问题没有与已存在的问题重复。
