name: "➕ 新命令请求"
description: 建议支持某个Git命令 (这并不意味这你需要实现它)
labels: ["DEV-需要注意", "新功能", "缺少"]
title: "[Feat(新命令)]: "
body:
  - type: checkboxes
    attributes:
      label: 在继续之前，请确认以下内容
      description: 在发布您的Issue之前，请确认以下内容。
      options:
        - label: 我已经搜索过已存在的Issue，并没有存在相同的正在进行中/重复/已解决的Issue
          required: true
        - label: 如果该命令在预览版中实现，我没有被告知
          required: true
        - label: 该命令是Git原有的命令，不用额外依赖 (我们不接受非Git原有的命令)
          required: true
  - type: dropdown
    attributes:
      label: 选择一个命令类别
      description: 是Git的命令还是中文Git的命令?
      options:
        - 请求支持新的Git命令
        - 请求新的中文Git命令
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你需要添加什么命令
      placeholder: 请在这里填写你需要添加的命令
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你需要添加的命令是做什么用的
      placeholder: 请在这里描述你需要添加的命令的作用
    validations:
      required: true
  - type: textarea
    attributes:
      label: 对于实施该功能的方法的建议 (可选)
      placeholder: 建议我们如何实现这一点 (建议填写此字段，这对实施很有帮助!)
    validations:
      required: false
