name: 自动验证在 Windows 上的打包版

on:
  push:
    branches:
      - pack_windows
  workflow_dispatch:

jobs:
  verify-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: 配置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: 签出分支
        run: |
          git config --global user.name '自动验证流'
          git config --global user.email 'github-actions@github.com'
          git checkout pack_windows

      - name: 验证打包版
        run: |
          powershell
          & ".\中文git.exe" 版本
          & ".\中文git更新程序.exe" --version 2.9

      - name: 配置拉取请求
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取头分支为 pack_windows的打开pr
          pr_number=$(gh pr list --state open --head pack_windows --json number -q '.[0].number')
          # 配置PR
          gh pr edit $pr_number --add-label "DEV-自动验证通过"
          gh pr review $pr_number --approve
