name: Build Python Executables on windows

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout to other branch
        run: |
          git config --global user.name '自动打包流'
          git config --global user.email 'github-actions@github.com'
          git checkout -b pack_windows

      - name: Install dependencies
        # 也许不用 npm install ?
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Delete old files
        run: |
          node .auto_script\del_old_files.js

      - name: Build executables
        run: |
          pyinstaller --onefile --distpath=. --name=中文git_windows 中文git-pack.py
          pyinstaller --onefile --distpath=. --name=中文git更新程序_windows 中文git更新程序.py

      - name: Commit windows executables
        run: |
          git add 中文git_windows 中文git更新程序_windows
          git commit -m "添加 windows 构建文件"
          git push --set-upstream origin pack_windows

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head pack_windows --title "Add windows Build Files" --body "This PR adds windows build files generated by GitHub Actions."
