name: Build Python Executables on Windows

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Checkout to other branch
        run: |
          git config --global user.name '自动打包流'
          git config --global user.email 'github-actions@github.com'
          git checkout -b pack_windows
          git merge main

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Delete old files
        run: |
          if exist "中文git更新程序.exe" (
            echo 找到旧文件【中文git更新程序.exe】，正在删除...
            del 中文git更新程序.exe
          ) else (
            echo 未找到旧文件【中文git更新程序.exe】
          )

          if exist "中文git.exe" (
            echo 找到旧文件【中文git.exe】，正在删除...
            del 中文git.exe
          ) else (
            echo 未找到旧文件【中文git.exe】
          )

      - name: Build executables
        run: |
          pyinstaller --onefile --distpath=. --name=中文git 中文git-pack.py
          pyinstaller --onefile --distpath=. --name=中文git更新程序 中文git更新程序.py

      - name: Commit Windows executables
        run: |
          git add 中文git.exe 中文git更新程序.exe
          git commit -m "添加 Windows 构建文件"
          git push --set-upstream origin pack --force
