name: 在 Macos 上打包 中文Git

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: 配置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: 签出分支
        run: |
          git config --global user.name '自动打包流'
          git config --global user.email 'github-actions@github.com'
          git checkout -b pack_macos

      - name: 安装依赖
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: 移除旧文件
        run: |
          python .auto_script/del_old_files.py

      - name: 打包构建
        run: |
          pyinstaller --onefile --distpath=. --name=中文git_macos 中文git-pack.py
          pyinstaller --onefile --distpath=. --name=中文git更新程序_macos 中文git更新程序.py

      - name: 提交结果
        run: |
          git add 中文git_macos 中文git更新程序_macos
          git commit -m "添加 Macos 构建文件"
          git push --set-upstream origin pack_macos

      - name: 创建拉取请求
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head pack_macos --title "Auto-pack: 添加对于 Macos 的构建文件" --body "添加由工作流自动打包的适用于 Macos 的中文Git"

      - name: 配置拉取请求
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取头分支为 pack_macos 的打开pr
          pr_number=$(gh pr list --state open --head pack_macos --json number -q '.[0].number')
          gh pr edit $pr_number --add-label "工作流-自动打包"
          # 请求审查员
          gh api -X POST /repos/${{ github.repository }}/pulls/$pr_number/requested_reviewers --input - <<EOF
          {
            "reviewers": ["DuckDuckStudio", "Luna-Grace"]
          }
          EOF
