name: Build Python Executables on macOS

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Delete old files
        run: |
          if [ -f "中文git更新程序_macos" ]; then
            echo "找到旧文件【中文git更新程序_macos】，正在删除..."
            rm 中文git更新程序_macos
          else
            echo "未找到旧文件【中文git更新程序_macos】"
          fi

          if [ -f "中文git_macos" ]; then
            echo "找到旧文件【中文git_macos】，正在删除..."
            rm 中文git_macos
          else
            echo "未找到旧文件【中文git_macos】"
          fi

      - name: Build executables
        run: |
          pyinstaller --onefile --distpath=. --name=中文git_macos 中文git-pack.py
          pyinstaller --onefile --distpath=. --name=中文git更新程序_macos 中文git更新程序.py

      - name: Commit macOS executables
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b pack_macos
          git add 中文git_macos 中文git更新程序_macos
          git commit -m "添加 macOS 构建文件"
          git push --set-upstream origin pack_macos

      - name: Install GitHub CLI
        uses: cli/cli

      - name: Create Pull Request for macOS
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh pr create --base main --head pack_macos --title "Add macOS build files" --body "This PR adds the macOS build executables."
